### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by maxtimbo** [open-condo-software/condo#4899]
I'm getting the following error:

```
$ node ./bin/prepare.js 
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /home/tfinley/condo/bin/prepare.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/tfinley/condo/bin/prepare.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/tfinley/condo/bin/prepare.js' ]
}
```

```
$ node -v
v16.20.2
```

I've tried to install commander globally, but that doesn't work either.

**Comment by SavelevMatthew** [comment]
Hi, it seems you missed the package installation part (`yarn`, `yarn install` or similar command for another package manager)

Because `commander` is explicitly listed in the monorepo root dependencies list:
https://github.com/open-condo-software/condo/blob/b40f67557b690dacf22d018e4ca200935a57294f/package.json#L41

**Comment by maxtimbo** [comment]
I just tried `npm install`:

```
$ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./domains
```

**Comment by SavelevMatthew** [comment]
Seems like it's some local problem happening, you can try reinstall yarn...

https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by maxtimbo** [comment]
Alright. Next command throws errors as well:

```
$ node ./bin/prepare.js

[. . .]

--> Preparing "condo" app
------> Copying app's .env.example values to .env if not exists
------> Writing assigned urls / ports / dbs to app's .env
------> Running migration script
Error: Command failed: yarn workspace @app/condo migrate
ERROR: can't get knex schema

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by maxtimbo** [comment]
I got here:

```
$ node ./bin/prepare.js 
--> Running sanity checks
--> Receiving all existing apps
--> Apps found: address-service, condo, dev-api, dev-portal, miniapp
--> Assigning ports, urls and db indexes/names to all apps
--> Copying global .env.example values to global .env if not exists
--> Writing services <service-name>_DOMAIN variables to global .env
--> Filtering apps to prepare: address-service, condo, dev-api, dev-portal, miniapp
--> Creating databases for apps if not exists: local-address-service, local-condo, local-dev-api, local-miniapp
--> Preparing "address-service" app
------> Copying app's .env.example values to .env if not exists
------> Writing assigned urls / ports / dbs to app's .env
------> Running migration script
(node:2580449) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

RUN "return await knex.migrate.latest(config)"
 -> [ 2, [] ]
--> Preparing "condo" app
------> Copying app's .env.example values to .env if not exists
------> Writing assigned urls / ports / dbs to app's .env
------> Running migration script
Error: Command failed: yarn workspace @app/condo migrate
ERROR: can't get knex schema

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'yarn workspace @app/condo migrate',
  stdout: 'ERROR: logfile = /home/tfinley/condo/apps/condo/.kmigrator/get.knex.settings.log\n' +
    'Browserslist: caniuse-lite is outdated. Please run:\n' +
    'npx browserslist@latest --update-db\n' +
    'hCaptcha not configured\n' +
    '/home/tfinley/condo/packages/keystone/KSv5v6/v5/prepareKeystone.js:233\n' +
    '        throw err\n' +
    '        ^\n' +
    '\n' +
    `Error: Cannot find module '/home/tfinley/condo/node_modules/@open-condo/icons/dist/index.js'. Please verify that the package.json has a valid "main" entry\n` +
    '    at tryPackage (node:internal/modules/cjs/loader:427:19)\n' +
    '    at Function.Module._findPath (node:internal/modules/cjs/loader:640:18)\n' +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:873:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1100:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:119:18)\n' +
    '    at Object.<anonymous> (/home/tfinley/condo/apps/condo/domains/miniapp/schema/fields/integration.js:1:18)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1076:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1100:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:119:18)\n' +
    '    at Object.<anonymous> (/home/tfinley/condo/apps/condo/domains/billing/schema/BillingIntegration.js:27:5)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    "  path: '/home/tfinley/condo/node_modules/@open-condo/icons/package.json',\n" +
    "  requestPath: '@open-condo/icons'\n" +
    '}\n' +
    '\n',
  stderr: "ERROR: can't get knex schema\n"
}
```

Please note, however, there were quite a few depreciation warnings when running `yarn`:

```
$ yarn
➤ YN0000: ┌ Project validation
➤ YN0057: │ @app/condo: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @apollographql/graphql-playground-react@npm:1.7.42 provides graphql (p5a641) with version 15.8.0, which doesn't satisfy what graphiql and some of its descendants request
➤ YN0060: │ @apollographql/graphql-playground-react@npm:1.7.42 provides react (p46764) with version 16.13.1, which doesn't satisfy what react-codemirror requests
➤ YN0060: │ @apollographql/graphql-playground-react@npm:1.7.42 provides react (pc235e) with version 16.13.1, which doesn't satisfy what react-dom requests
➤ YN0060: │ @apollographql/graphql-playground-react@npm:1.7.42 provides react-dom (p9eac0) with version 16.14.0, which doesn't satisfy what react-codemirror requests
➤ YN0002: │ @app/address-service@workspace:apps/address-service doesn't provide @babel/core (pb5061), requested by babel-jest
➤ YN0002: │ @app/address-service@workspace:apps/address-service doesn't provide @babel/core (paf357), requested by @emotion/babel-plugin
➤ YN0060: │ @app/address-service@workspace:apps/address-service provides jest (p97b80) with version 29.7.0, which doesn't satisfy what jest-watch-typeahead requests
➤ YN0060: │ @app/address-service@workspace:apps/address-service provides less (pec7eb) with version 3.13.1, which doesn't satisfy what @zeit/next-less and some of its descendants request
➤ YN0060: │ @app/address-service@workspace:apps/address-service provides react (pf3890) with version 16.14.0, which doesn't satisfy what @keystonejs/fields-color and some of its descendants request
➤ YN0060: │ @app/address-service@workspace:apps/address-service provides react (p39f30) with version 16.14.0, which doesn't satisfy what react-fittext requests
➤ YN0060: │ @app/address-service@workspace:apps/address-service provides react-dom (pe1f45) with version 16.14.0, which doesn't satisfy what react-fittext requests
➤ YN0002: │ @app/address-service@workspace:apps/address-service doesn't provide webpack (pcead7), requested by @zeit/next-css
➤ YN0002: │ @app/address-service@workspace:apps/address-service doesn't provide webpack (p455e1), requested by @zeit/next-less
➤ YN0002: │ @app/condo@workspace:apps/condo doesn't provide @babel/core (pfa916), requested by babel-jest
➤ YN0002: │ @app/condo@workspace:apps/condo doesn't provide @babel/core (pee828), requested by @emotion/babel-plugin
➤ YN0060: │ @app/condo@workspace:apps/condo provides graphql (p6536a) with version 15.8.0, which doesn't satisfy what graphql-upload requests
➤ YN0060: │ @app/condo@workspace:apps/condo provides jest (p89d66) with version 29.7.0, which doesn't satisfy what jest-watch-typeahead requests
➤ YN0060: │ @app/condo@workspace:apps/condo provides less (pd1707) with version 3.13.1, which doesn't satisfy what @zeit/next-less requests
➤ YN0060: │ @app/condo@workspace:apps/condo provides react (pc9a61) with version 16.14.0, which doesn't satisfy what @keystonejs/fields-color and some of its descendants request
➤ YN0060: │ @app/condo@workspace:apps/condo provides react (p2c055) with version 16.14.0, which doesn't satisfy what react-fittext requests
➤ YN0060: │ @app/condo@workspace:apps/condo provides react (p00e05) with version 16.14.0, which doesn't satisfy what react-google-recaptcha-v3 requests
➤ YN0060: │ @app/condo@workspace:apps/condo provides react-dom (pdc63f) with version 16.14.0, which doesn't satisfy what react-fittext requests
➤ YN0060: │ @app/condo@workspace:apps/condo provides react-dom (pa84f9) with version 16.14.0, which doesn't satisfy what react-google-recaptcha-v3 requests
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide @apollo/client (p21b9e), requested by @open-condo/apollo-server-client
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide @babel/core (p90584), requested by babel-jest
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide apollo-link-error (p91078), requested by @open-condo/apollo-server-client
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide apollo-upload-client (pb62ae), requested by @open-condo/apollo-server-client
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide cross-fetch (p22999), requested by @open-condo/apollo-server-client
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide graphql (p0b280), requested by @keystonejs/app-graphql-playground
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide graphql (p3c2be), requested by @open-condo/apollo-server-client
➤ YN0060: │ @app/dev-api@workspace:apps/dev-api provides jest (pde16a) with version 29.7.0, which doesn't satisfy what jest-watch-typeahead requests
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide react (p8948f), requested by @keystonejs/fields-color
➤ YN0002: │ @app/dev-api@workspace:apps/dev-api doesn't provide react (p85004), requested by @open-condo/apollo-server-client
➤ YN0002: │ @app/dev-portal@workspace:apps/dev-portal doesn't provide @types/node (p0c0ea), requested by ts-node
➤ YN0060: │ @app/dev-portal@workspace:apps/dev-portal provides react (pe4ec0) with version 18.2.0, which doesn't satisfy what @open-condo/next and some of its descendants request
➤ YN0060: │ @app/dev-portal@workspace:apps/dev-portal provides react (p696b4) with version 18.2.0, which doesn't satisfy what @open-condo/ui and some of its descendants request
➤ YN0060: │ @app/dev-portal@workspace:apps/dev-portal provides react-dom (pe819d) with version 18.2.0, which doesn't satisfy what @open-condo/next and some of its descendants request
➤ YN0060: │ @app/dev-portal@workspace:apps/dev-portal provides react-dom (pf31c6) with version 18.2.0, which doesn't satisfy what @open-condo/ui and some of its descendants request
➤ YN0002: │ @app/miniapp@workspace:apps/miniapp doesn't provide @babel/core (p8e90c), requested by babel-jest
➤ YN0002: │ @app/miniapp@workspace:apps/miniapp doesn't provide @babel/core (p4c905), requested by @emotion/babel-plugin
➤ YN0060: │ @app/miniapp@workspace:apps/miniapp provides jest (pe7e00) with version 29.7.0, which doesn't satisfy what jest-watch-typeahead requests
➤ YN0060: │ @app/miniapp@workspace:apps/miniapp provides less (pbe267) with version 3.13.1, which doesn't satisfy what @zeit/next-less requests
➤ YN0060: │ @app/miniapp@workspace:apps/miniapp provides react (pb1f0b) with version 16.14.0, which doesn't satisfy what @keystonejs/fields-color and some of its descendants request
➤ YN0060: │ @app/miniapp@workspace:apps/miniapp provides react (p6e75a) with version 16.14.0, which doesn't satisfy what react-fittext requests
➤ YN0060: │ @app/miniapp@workspace:apps/miniapp provides react-dom (pf2062) with version 16.14.0, which doesn't satisfy what react-fittext requests
➤ YN0002: │ @arch-ui/button@npm:0.0.25 [042fc] doesn't provide react-dom (pc1e30), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/button@npm:0.0.25 [2f0a1] doesn't provide react-dom (pbe9fc), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/button@npm:0.0.25 [6b1c6] doesn't provide react-dom (pf00cc), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/button@npm:0.0.25 [76f9b] doesn't provide react-dom (p7c334), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/button@npm:0.0.25 [886da] doesn't provide react-dom (p83a2b), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/confirm@npm:0.0.26 [042fc] doesn't provide prop-types (p365a6), requested by focus-trap-react
➤ YN0002: │ @arch-ui/controls@npm:0.1.12 [042fc] doesn't provide react-dom (pb6ee3), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/controls@npm:0.1.12 [042fc] doesn't provide react-dom (pfd984), requested by react-radios
➤ YN0002: │ @arch-ui/controls@npm:0.1.12 [6b1c6] doesn't provide react-dom (pa4e2a), requested by react-pseudo-state
➤ YN0002: │ @arch-ui/controls@npm:0.1.12 [6b1c6] doesn't provide react-dom (pd5fae), requested by react-radios
➤ YN0002: │ @arch-ui/day-picker@npm:1.0.8 [6b1c6] doesn't provide react-dom (p51161), requested by react-window
➤ YN0002: │ @arch-ui/dialog@npm:0.0.28 [042fc] doesn't provide prop-types (pda4fa), requested by focus-trap-react
➤ YN0002: │ @arch-ui/drawer@npm:0.0.28 [042fc] doesn't provide prop-types (p8866f), requested by focus-trap-react
➤ YN0002: │ @arch-ui/drawer@npm:0.0.28 [6b1c6] doesn't provide prop-types (pab9ae), requested by focus-trap-react
➤ YN0002: │ @arch-ui/dropdown@npm:0.0.25 [042fc] doesn't provide prop-types (pc03a4), requested by focus-trap-react
➤ YN0002: │ @arch-ui/filters@npm:0.0.23 [6b1c6] doesn't provide react-dom (pbaff7), requested by react-radios
➤ YN0002: │ @arch-ui/modal-utils@npm:1.0.16 [3acbb] doesn't provide react-dom (p7ff41), requested by react-transition-group
➤ YN0002: │ @arch-ui/modal-utils@npm:1.0.16 [43aae] doesn't provide react-dom (p4e552), requested by react-transition-group
➤ YN0002: │ @arch-ui/modal-utils@npm:1.0.16 [9834f] doesn't provide react-dom (p76343), requested by react-transition-group
➤ YN0002: │ @arch-ui/modal-utils@npm:1.0.16 [9a119] doesn't provide react-dom (pc9d58), requested by react-transition-group
➤ YN0002: │ @arch-ui/modal-utils@npm:1.0.16 [cbc4b] doesn't provide react-dom (p606e6), requested by react-transition-group
➤ YN0002: │ @arch-ui/options@npm:0.0.27 [042fc] doesn't provide react-dom (p2a346), requested by react-select
➤ YN0002: │ @arch-ui/options@npm:0.0.27 [6b1c6] doesn't provide react-dom (pdf11c), requested by react-select
➤ YN0002: │ @arch-ui/popout@npm:0.0.26 [042fc] doesn't provide prop-types (p8453a), requested by focus-trap-react
➤ YN0002: │ @arch-ui/popout@npm:0.0.26 [2f0a1] doesn't provide prop-types (pf3d29), requested by focus-trap-react
➤ YN0002: │ @arch-ui/popout@npm:0.0.26 [6b1c6] doesn't provide prop-types (p4c50d), requested by focus-trap-react
➤ YN0002: │ @arch-ui/popout@npm:0.0.26 [76f9b] doesn't provide prop-types (p47033), requested by focus-trap-react
➤ YN0002: │ @arch-ui/popout@npm:0.0.26 [886da] doesn't provide prop-types (p21f9f), requested by focus-trap-react
➤ YN0002: │ @arch-ui/select@npm:0.1.12 [042fc] doesn't provide react-dom (p44821), requested by react-select
➤ YN0002: │ @arch-ui/select@npm:0.1.12 [6b1c6] doesn't provide react-dom (pf4298), requested by react-select
➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [1c864] doesn't provide react-dom (p46cd3), requested by @design-systems/utils
➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [21404] doesn't provide react-dom (pad13d), requested by @design-systems/utils
➤ YN0002: │ @endemolshinegroup/cosmiconfig-typescript-loader@npm:3.0.2 [f97f3] doesn't provide typescript (p70c07), requested by ts-node
➤ YN0002: │ @firebase/auth@npm:0.15.0 [a1f70] doesn't provide @firebase/app-types (pba397), requested by @firebase/auth-types
➤ YN0002: │ @firebase/auth@npm:0.15.0 [a1f70] doesn't provide @firebase/util (p55d29), requested by @firebase/auth-types
➤ YN0002: │ @firebase/database@npm:0.13.5 doesn't provide @firebase/app-types (p76314), requested by @firebase/auth-interop-types
➤ YN0002: │ @firebase/database@npm:0.6.13 doesn't provide @firebase/app-types (p7a262), requested by @firebase/auth-interop-types
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react (p13053) with version 17.0.2, which doesn't satisfy what @arch-ui/button and some of its descendants request
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react (pdae6e) with version 17.0.2, which doesn't satisfy what @arch-ui/confirm and some of its descendants request
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react (p4c0cf) with version 17.0.2, which doesn't satisfy what @arch-ui/controls and some of its descendants request
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react (p1b941) with version 17.0.2, which doesn't satisfy what react-prop-toggle requests
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react (p78921) with version 17.0.2, which doesn't satisfy what react-pseudo-state requests
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react-dom (p22174) with version 17.0.2, which doesn't satisfy what react-prop-toggle requests
➤ YN0060: │ @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm%3A7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::version=7.5.2&hash=e87992&locator=root%40workspace%3A. provides react-dom (p2b9c7) with version 17.0.2, which doesn't satisfy what react-pseudo-state requests
➤ YN0060: │ @keystonejs/app-graphql@patch:@keystonejs/app-graphql@npm%3A6.3.2#.yarn/patches/@keystonejs-app-graphql-npm-6.3.2-26fe50b988.patch::version=6.3.2&hash=c39a71&locator=root%40workspace%3A. [fe6a8] provides graphql (pd445b) with version 15.8.0, which doesn't satisfy what graphql-upload requests
➤ YN0002: │ @keystonejs/fields-color@npm:1.1.2 [ca2fd] doesn't provide react-dom (p6a7f0), requested by @arch-ui/popout
➤ YN0002: │ @keystonejs/fields-color@npm:1.1.2 [e8768] doesn't provide react-dom (pf9943), requested by @arch-ui/popout
➤ YN0002: │ @keystonejs/fields-color@npm:1.1.2 [fe6a8] doesn't provide react-dom (p0a57c), requested by @arch-ui/popout
➤ YN0060: │ @keystonejs/fields-location-google@npm:3.4.2 provides react (p04b57) with version 17.0.2, which doesn't satisfy what google-maps-react requests
➤ YN0002: │ @keystonejs/fields-location-google@npm:3.4.2 doesn't provide react-dom (p52b81), requested by google-maps-react
➤ YN0002: │ @keystonejs/fields-location-google@npm:3.4.2 doesn't provide react-dom (p74494), requested by react-toast-notifications
➤ YN0060: │ @keystonejs/fields-markdown@npm:5.3.2 provides react (paac70) with version 17.0.2, which doesn't satisfy what react-codemirror2 requests
➤ YN0002: │ @keystonejs/fields-markdown@npm:5.3.2 doesn't provide react-dom (p6ed68), requested by @arch-ui/tooltip
➤ YN0002: │ @keystonejs/fields-wysiwyg-tinymce@npm:5.4.2 [fe6a8] doesn't provide react-dom (p78f23), requested by @tinymce/tinymce-react
➤ YN0060: │ @keystonejs/fields@npm:22.1.3 provides react (ped973) with version 17.0.2, which doesn't satisfy what @arch-ui/controls and some of its descendants request
➤ YN0060: │ @keystonejs/fields@npm:22.1.3 provides react (pfbc56) with version 17.0.2, which doesn't satisfy what @arch-ui/button and some of its descendants request
➤ YN0060: │ @keystonejs/fields@npm:22.1.3 provides react (pab74a) with version 17.0.2, which doesn't satisfy what @arch-ui/drawer and some of its descendants request
➤ YN0060: │ @keystonejs/fields@npm:22.1.3 provides react (p9e0c6) with version 17.0.2, which doesn't satisfy what react-day-picker requests
➤ YN0060: │ @keystonejs/keystone@patch:@keystonejs/keystone@npm%3A19.3.4#.yarn/patches/@keystonejs-keystone-npm-19.3.4-2a53e53061.patch::version=19.3.4&hash=3c7fde&locator=root%40workspace%3A. provides graphql (p03b2b) with version 15.8.0, which doesn't satisfy what graphql-upload requests
➤ YN0002: │ @open-condo/bridge@workspace:packages/bridge doesn't provide @babel/core (p2e6c7), requested by rollup-plugin-babel
➤ YN0060: │ @open-condo/bridge@workspace:packages/bridge provides rollup (pd7396) with version 2.79.1, which doesn't satisfy what rollup-plugin-uglify requests
➤ YN0002: │ @open-condo/featureflags@workspace:packages/featureflags doesn't provide react-dom (peea15), requested by @open-condo/next
➤ YN0002: │ @open-condo/featureflags@workspace:packages/featureflags [acf11] doesn't provide react-dom (p473d7), requested by @open-condo/next
➤ YN0002: │ @open-condo/keystone@workspace:packages/keystone doesn't provide @babel/core (pe4a4d), requested by babel-jest
➤ YN0002: │ @open-condo/keystone@workspace:packages/keystone doesn't provide @types/tough-cookie (p6b66b), requested by axios-cookiejar-support
➤ YN0060: │ @open-condo/keystone@workspace:packages/keystone provides graphql (p9ed4f) with version 15.8.0, which doesn't satisfy what graphql-upload requests
➤ YN0060: │ @open-condo/keystone@workspace:packages/keystone provides react (p73178) with version 16.14.0, which doesn't satisfy what @keystonejs/fields-color and some of its descendants request
➤ YN0002: │ @open-condo/keystone@workspace:packages/keystone doesn't provide react-dom (pd9633), requested by @apollo/client
➤ YN0002: │ @open-condo/keystone@workspace:packages/keystone doesn't provide react-dom (p83f31), requested by @keystonejs/app-next
➤ YN0002: │ @open-condo/ui@workspace:packages/ui doesn't provide require-from-string (pc1d6e), requested by @storybook/react
➤ YN0002: │ @open-condo/ui@workspace:packages/ui [acf11] doesn't provide require-from-string (p4cc19), requested by @storybook/react
➤ YN0002: │ @open-condo/ui@workspace:packages/ui [d9f70] doesn't provide require-from-string (p6e1e2), requested by @storybook/react
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8354] doesn't provide @babel/core (p32299), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8354] doesn't provide @babel/core (p2ecf9), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8354] doesn't provide @babel/core (p5a3fd), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8354] doesn't provide webpack (p86e8e), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8b72] doesn't provide @babel/core (pdd59b), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8b72] doesn't provide @babel/core (pf8f63), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8b72] doesn't provide @babel/core (p36bf9), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [b8b72] doesn't provide webpack (p0f50f), requested by babel-loader
➤ YN0002: │ @storybook/docs-tools@npm:6.5.16 doesn't provide react (p9b542), requested by @storybook/store
➤ YN0002: │ @storybook/docs-tools@npm:6.5.16 doesn't provide react-dom (pc910b), requested by @storybook/store
➤ YN0002: │ @storybook/instrumenter@npm:6.5.10 doesn't provide react (p5478e), requested by @storybook/addons
➤ YN0002: │ @storybook/instrumenter@npm:6.5.10 doesn't provide react-dom (p664ad), requested by @storybook/addons
➤ YN0002: │ @storybook/mdx1-csf@npm:0.0.1 doesn't provide @babel/core (p59aa6), requested by @babel/preset-env
➤ YN0002: │ @storybook/telemetry@npm:6.5.16 doesn't provide react (p48f29), requested by @storybook/core-common
➤ YN0002: │ @storybook/telemetry@npm:6.5.16 doesn't provide react-dom (p479a1), requested by @storybook/core-common
➤ YN0002: │ apollo-link-ws@npm:1.0.8 [ebfc8] doesn't provide graphql (pc76b4), requested by apollo-link
➤ YN0002: │ apollo-upload-client@npm:14.1.3 [042fc] doesn't provide react-dom (pd1185), requested by @apollo/client
➤ YN0002: │ graphql-config@npm:4.3.3 [72ac1] doesn't provide @types/node (p9df9b), requested by cosmiconfig-typescript-loader
➤ YN0002: │ graphql-config@npm:4.3.3 [72ac1] doesn't provide @types/node (p836a8), requested by ts-node
➤ YN0002: │ graphql-config@npm:4.3.3 [72ac1] doesn't provide typescript (p7d750), requested by cosmiconfig-typescript-loader
➤ YN0002: │ graphql-config@npm:4.3.3 [72ac1] doesn't provide typescript (p083ee), requested by ts-node
➤ YN0002: │ root@workspace:. doesn't provide @babel/core (p83e50), requested by @babel/plugin-proposal-private-methods
➤ YN0002: │ root@workspace:. doesn't provide @commitlint/lint (p8c961), requested by commitlint-plugin-function-rules
➤ YN0002: │ root@workspace:. doesn't provide graphql (p793b3), requested by @graphql-codegen/cli
➤ YN0002: │ root@workspace:. doesn't provide graphql (p084a0), requested by @graphql-codegen/typescript
➤ YN0002: │ root@workspace:. doesn't provide next (p67ceb), requested by @sentry/nextjs
➤ YN0002: │ root@workspace:. doesn't provide react (pc17f3), requested by @sentry/nextjs
➤ YN0002: │ unstated@npm:2.1.1 [bfc5e] doesn't provide prop-types (pcdf5c), requested by create-react-context
➤ YN0002: │ unstated@npm:2.1.1 [ccca1] doesn't provide prop-types (p966eb), requested by create-react-context
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 3s 463ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0069: │ @apollo/client ➤ peerDependencies ➤ react: This rule seems redundant when applied on the original package; the extension may have been applied upstream.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 9s 531ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 13s 366ms
➤ YN0000: Done with warnings in 29s 240ms
```

**Comment by toplenboren** [comment]
Hi! Sorry for the delayed answer

To fix: `Cannot find module '/home/tfinley/condo/node_modules/@open-condo/icons/dist/index.js` try building `@open-condo/icons` first

`yarn workspace @open-condo/icons` 

You can also try building whole UI

`yarn workspace @open-condo/ui` 

--

P.S We know about this bug, running migrations should not depend on any frontend code, I think we will fix it in near future

**Comment by maxtimbo** [comment]
>To fix: Cannot find module '/home/tfinley/condo/node_modules/@open-condo/icons/dist/index.js try building @open-condo/icons first

Tried that. It led me down a chatgpt fueled rabbit hole trying this and other similar attempts. You might try spinning up a VM and trying to get through the install. I feel like it shouldn't be this difficult.

**Comment by pahaz** [comment]
Sorry, we update our README.md, could you please follow this instructions and provide console output:

```
# 1) Clone the repo
git clone git@github.com:open-condo-software/open-condo-platform.git condo
cd condo

# 2) Install dependencies and link workspaces
yarn
python3 -m pip install django
python3 -m pip install psycopg2-binary

# 3) startup redis and postgres
docker-compose up -d postgresdb redis

# 4.1) prepare packages
yarn workspace @open-condo/icons build
yarn workspace @open-condo/ui build
yarn workspace @open-condo/bridge build
# 4.2) prepare apps
node ./bin/prepare.js

# START CONDO APP
yarn workspace @app/condo build
yarn workspace @app/condo maketypes
yarn workspace @app/condo start
```

**Comment by SavelevMatthew** [comment]
Hi there ✋ 

We've started getting a few messages recently about not being able to build the project locally. So I've made a few changes that should combat this:
1. [In this PR](https://github.com/open-condo-software/condo/pull/5689), I've added a CI checker that verifies that the open-source part of the project can be built on all Linux / Windows devices (Mac is also supported, but without CI, since it similar to Linux).
2. And I also updated the README of the project, making it more detailed and step-by-step, repeating the steps from CI

Now we are sure that the project should build on all modern devices 🥳 

Let me know in a new issue if problems remain. Thanks for your patience 🙏
