### ISSUE TITLE
Prepare.js failed with error

### ISSUE THREAD

**Issue by pahaz** [open-condo-software/condo#5428]
I'm trying to follow the `README.md`:

```
user@open-condo-research % node ./bin/prepare.js                                                   
--> Running sanity checks
--> Receiving all existing apps
--> Apps found: address-service, announcement-generator, asterix_bot, callcenter, classifiers-api, condo, condo-news-sharing-greendom, condo-restapi, condorb, dev-api, dev-portal, documents-next, eds-mosreg-integration, eps, insurance, meters-billing-integration, miniapp, pass, property-importer, registry, resident-app, telegram-employee-bot, telephony, telephony-integration
--> Assigning ports, urls and db indexes/names to all apps
--> Copying global .env.example values to global .env if not exists
--> Writing services <service-name>_DOMAIN variables to global .env
--> Filtering apps to prepare: address-service, condo, dev-api, dev-portal, miniapp
--> Creating databases for apps if not exists: local-address-service, local-condo, local-dev-api, local-miniapp
--> Preparing "address-service" app
------> Copying app's .env.example values to .env if not exists
------> Writing assigned urls / ports / dbs to app's .env
------> Running migration script
{"level":30,"time":1730820369452,"pid":44823,"hostname":"PahazMac16.local","name":"asyncLocalStorage","msg":"getAsyncLocalStorage new storage to be created","args":"[\"executionCtx\"]"}
{"level":30,"time":1730820370676,"pid":44823,"hostname":"PahazMac16.local","name":"asyncLocalStorage","msg":"getAsyncLocalStorage new storage to be created","args":"[\"graphqlCtx\"]"}
{"level":30,"time":1730820372343,"pid":44823,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"worker:tasks:client","opts":"{\"enableReadyCheck\":false,\"port\":6379,\"host\":\"127.0.0.1\"}"}
{"level":30,"time":1730820372345,"pid":44823,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"default:regular","opts":"{}"}
(node:44823) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:44823) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./public/" in the "exports" field module resolution of the package at /Users/pahaz/Code/pahaz/open-condo-research/node_modules/extract-files/package.json.
Update this package.json to use a subpath pattern like "./public/*".
{"level":30,"time":1730820372384,"pid":44823,"hostname":"PahazMac16.local","name":"redis","msg":"connect","clientKey":"worker:tasks:client"}
{"level":30,"time":1730820372384,"pid":44823,"hostname":"PahazMac16.local","name":"redis","msg":"connect","clientKey":"default:regular"}

RUN "return await knex.migrate.latest(config)"
 -> [
  1,
  [
    '20220819090735-0001_initial.js',
    '20221124181138-0002_address_addresshistoryrecord_and_more.js',
    '20230216132102-0003_address_overrides_addresshistoryrecord_overrides.js',
    '20230216132102-0004_manual_lowercase_address_source.js'
  ]
]
--> Preparing "condo" app
------> Copying app's .env.example values to .env if not exists
------> Writing assigned urls / ports / dbs to app's .env
------> Running migration script
Error: Command failed: yarn workspace @app/condo migrate
ERROR: can't get knex schema

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'yarn workspace @app/condo migrate',
  stdout: 'ERROR: logfile = /Users/pahaz/Code/pahaz/open-condo-research/apps/condo/.kmigrator/get.knex.settings.log\n' +
    'Browserslist: caniuse-lite is outdated. Please run:\n' +
    'npx browserslist@latest --update-db\n' +
    '{"level":30,"time":1730820377121,"pid":44830,"hostname":"PahazMac16.local","name":"asyncLocalStorage","msg":"getAsyncLocalStorage new storage to be created","args":"[\\"executionCtx\\"]"}\n' +
    '{"level":40,"time":1730820378336,"pid":44830,"hostname":"PahazMac16.local","name":"featureToggleManager","msg":"No FEATURE_TOGGLE_CONFIG! Every features and values will be false!"}\n' +
    '{"level":30,"time":1730820380139,"pid":44830,"hostname":"PahazMac16.local","name":"asyncLocalStorage","msg":"getAsyncLocalStorage new storage to be created","args":"[\\"graphqlCtx\\"]"}\n' +
    '{"level":30,"time":1730820380616,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"worker:regular","opts":"{}"}\n' +
    '{"level":30,"time":1730820381031,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"default:regular","opts":"{}"}\n' +
    'hCaptcha not configured\n' +
    '{"level":50,"time":1730820381358,"pid":44830,"hostname":"PahazMac16.local","name":"hCaptcha","msg":"hCaptcha not configured"}\n' +
    '{"level":30,"time":1730820381396,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"default:regular","opts":"{}"}\n' +
    '{"level":30,"time":1730820381426,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"default:cache","opts":"{}"}\n' +
    '{"level":30,"time":1730820381434,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"default:cache","opts":"{}"}\n' +
    '{"level":30,"time":1730820381566,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"default:regular","opts":"{}"}\n' +
    '{"level":30,"time":1730820381795,"pid":44830,"hostname":"PahazMac16.local","name":"redis","msg":"getRedisClient","clientKey":"discoverServiceConsumersCronTask:regular","opts":"{}"}\n' +
    `{"level":50,"time":1730820382444,"pid":44830,"hostname":"PahazMac16.local","name":"uncaughtError","msg":"uncaughtException","err":{"type":"Error","message":"Cannot find module '/Users/pahaz/Code/pahaz/open-condo-research/node_modules/@open-condo/icons/dist/index.js'. Please verify that the package.json has a valid \\"main\\" entry","stack":"Error: Cannot find module '/Users/pahaz/Code/pahaz/open-condo-research/node_modules/@open-condo/icons/dist/index.js'. Please verify that the package.json has a valid \\"main\\" entry\\n    at tryPackage (node:internal/modules/cjs/loader:425:19)\\n    at Function.Module._findPath (node:internal/modules/cjs/loader:638:18)\\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)\\n    at Function.Module._load (node:internal/modules/cjs/loader:871:27)\\n    at Module.require (node:internal/modules/cjs/loader:1098:19)\\n    at require (node:internal/modules/cjs/helpers:108:18)\\n    at Object.<anonymous> (/Users/pahaz/Code/pahaz/open-condo-research/apps/condo/domains/miniapp/schema/fields/integration.js:1:18)\\n    at Module._compile (node:internal/modules/cjs/loader:1196:14)\\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)\\n    at Module.load (node:internal/modules/cjs/loader:1074:32)\\n    at Function.Module._load (node:internal/modules/cjs/loader:909:12)\\n    at Module.require (node:internal/modules/cjs/loader:1098:19)\\n    at require (node:internal/modules/cjs/helpers:108:18)\\n    at Object.<anonymous> (/Users/pahaz/Code/pahaz/open-condo-research/apps/condo/domains/billing/schema/BillingIntegration.js:27:5)\\n    at Module._compile (node:internal/modules/cjs/loader:1196:14)\\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)","code":"MODULE_NOT_FOUND","path":"/Users/pahaz/Code/pahaz/open-condo-research/node_modules/@open-condo/icons/package.json","requestPath":"@open-condo/icons"},"origin":"uncaughtException"}\n` +
    '/Users/pahaz/Code/pahaz/open-condo-research/packages/keystone/KSv5v6/v5/prepareKeystone.js:270\n' +
    '        throw err\n' +
    '        ^\n' +
    '\n' +
    `Error: Cannot find module '/Users/pahaz/Code/pahaz/open-condo-research/node_modules/@open-condo/icons/dist/index.js'. Please verify that the package.json has a valid "main" entry\n` +
    '    at tryPackage (node:internal/modules/cjs/loader:425:19)\n' +
    '    at Function.Module._findPath (node:internal/modules/cjs/loader:638:18)\n' +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:871:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1098:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:108:18)\n' +
    '    at Object.<anonymous> (/Users/pahaz/Code/pahaz/open-condo-research/apps/condo/domains/miniapp/schema/fields/integration.js:1:18)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1196:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1074:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:909:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1098:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:108:18)\n' +
    '    at Object.<anonymous> (/Users/pahaz/Code/pahaz/open-condo-research/apps/condo/domains/billing/schema/BillingIntegration.js:27:5)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1196:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    "  path: '/Users/pahaz/Code/pahaz/open-condo-research/node_modules/@open-condo/icons/package.json',\n" +
    "  requestPath: '@open-condo/icons'\n" +
    '}\n' +
    '\n',
  stderr: "ERROR: can't get knex schema\n"
}
```

**Comment by pahaz** [comment]
fixed by (https://github.com/open-condo-software/condo/pull/5439) and (https://github.com/open-condo-software/condo/pull/5437)
